from os import listdir
import os
from os.path import isfile, join

"""This function takes all of the text files generated by vernissage xy exporter in a specified folder 
and trims the metadata so that kolxpd can analyze the curvess.
This will go through all of the text files in the folder and all subfolders and make a copy where any 
row starting with # is removed up to the first row that doesn't start with #.  The copy is made in the 
folder the file is in """


#mypath = '/Users/apple/Documents/Research/XPS Analysis'
mypath = input("input folder path: ")
if not (os.path.isdir(mypath)):
    raise NameError('path is not a directory')

def list_files(dir):
    r = []
    for root, dirs, files in os.walk(dir):
        for name in files:
            r.append(os.path.join(root, name))
    return r


onlyfiles = list_files(mypath)
print(onlyfiles)

for i in onlyfiles:

    (dirname, filename) = os.path.split(i)
    filename = 'copy_' + filename
    copyname = os.path.join(dirname, filename)

    if ("copy" in i) or ("igor" in i):
        continue
    elif ".txt" in i:
        pass
    else:
        continue

    print(i)
    f = open(i)
    file_contents = f.readlines()
    f.close()

    while file_contents[0].startswith('#'):
        del(file_contents[0])



    copy = open(copyname, "w")
    for lines in file_contents:
        copy.write('%s' % lines)

    copy.close()




