#This function takes all of the text files generated by vernissage xy exporter in a specified folder
# and trims the metadata so that kolxpd can analyze the curves easily
#this will go through all of the text files in the folder regardless of what they actually are and make a copy
#where any row starting with # is removed up to the first row that doesn't start with #


from os import listdir
from os.path import isfile, join

#mypath = '/Users/apple/Documents/Research/XPS Analysis'
mypath = input("input folder path")
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

for i in onlyfiles:

    if ("copy" in i) or ("igor" in i):
        continue
    elif ".txt" in i:
        pass
    else:
        continue
    filepath = mypath + '/' + i
    print(filepath)
    f = open(filepath)
    file_contents = f.readlines()
    f.close()

    while file_contents[0].startswith('#'):
        del(file_contents[0])

    copyname = mypath+'/'+'copy'+i
    copy = open(copyname, "w")
    for lines in file_contents:
        copy.write('%s' % lines)

    copy.close()




