'''
This script looks at XPS snapshots in the format generated by the xy-exporter from vernissage
- Imports data from a specified file
- Removes non-data values and saves the kinetic energy and intensity in a
text file where each row consist of the kinetic energy value followed by the
sum of the intensities at that value
- Saves data in a numpy array for future use
'''


import matplotlib.pyplot as plt
import numpy as np

filepath = input( "Input file path: ") #input the full file path, example: D:\Documents\Grad School\20210721-114857_elena nicr sample--ESp_Cayman_iXPS--61_1-Detector_Region.txt
filepath = filepath.strip()
with open(filepath) as f:
    lines = f.readlines()
str_dataset = []
dataset = []   # this becomes your full dataset by the end, in python list format
for row in lines:
    if row.find('#') == -1:
        row_split = row.split()

        new_row = []
        row_str = ''                    #accumulators
        intensity_sum = 0

        for element in row_split:
            try:
                num_element = float(element)
                if row_split.index(element) == 0:
                    new_row.append(num_element)
                    row_str += element + '\t'
                else:
                    intensity_sum += num_element
            except:
                pass
        row_str += str(intensity_sum) + '\n'
        str_dataset.append(row_str)
        new_row.append(intensity_sum)
        dataset.append(new_row)


data = np.array(dataset) #converts the data to a numpy array
diffdata = np.gradient(data[:,1])
averagediff = np.average(diffdata)
stddiff = np.std(diffdata)
outlierlist = []
averagintensity = np.average(data[:,1])
stdintensity = np.std(data[:,1])
for i in range(len(diffdata)):
    if (abs(diffdata[i]-averagediff) > 3*stddiff):
        outlierlist = np.append(outlierlist, int(i))
        data[i,1] = np.nan
    elif(abs(data[i,1]-averagintensity) > 3*stdintensity):
        outlierlist = np.append(outlierlist, int(i))
        data[i,1] = np.nan
    elif((i<=2) and len(diffdata)>=3):
        outlierlist = np.append(outlierlist, int(i))
        data[i,1] = np.nan
    elif((len(diffdata)-i) <=3):
        outlierlist = np.append(outlierlist, int(i))
        data[i,1] = np.nan

#outlierlist = [int(x) for x in outlierlist]
#data = np.delete(data, outlierlist, 0)
plt.plot(1486.7-data[:,0], data[:,1])
plt.show()


#new_filename = input('Input new filename: ') # add .txt to the end, example: data.txt
#with open(new_filename, 'w') as output_text: # saves to your pycharm project folder which normally follows the path C:\Users\Your_Username\PycharmProjects\YourProjectName
#    output_text.writelines(str_dataset)

